// sql문을 보관함으로서 시간이 지났을때도 소스와 db간의 관계를 파악하기 용이
drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);